### ISSUE TITLE
windows 10 performance issues

### ISSUE THREAD

**Issue by morgvanny** [micahshute/wsl-setup#6]
I've got a student whose wsl setup quit working. a bunch of init processes pop up every time he tries to use it, and eat up his processing power, and never load. I found other people started having similar issues recently after a Windows 10 update. this may or may not be fixed in a subsequent update, but this solution proposed [here](https://www.reddit.com/r/bashonubuntuonwindows/comments/fbwpkn/latest_windows_build_18363693_breaks_node_in_wsl/fji0eag?utm_source=share&utm_medium=web2x) appears to have been successful for multiple people

update - my student followed instructions [here](https://teckangaroo.com/enable-windows-10-virtual-machine-platform/) and it solved the problem for him as well. Idk if we want to link this in the readme, or just insert an extra step into our guide showing how to change the setting

**Comment by maxwellbenton** [comment]
Hey @morgvanny,

I've added in the extra step of enabling Virtual Machine Platform based on the instructions you linked. I did not experience any issues on my personal machine after I updated Window 10, but enabling VMP also didn't cause any issues, so I believe it should be fine to include in for all students. Let me know if there are any other issues related to this.

CC'ing @micahshute here as well - Micah, do you mind glancing over the instructions to see if the changes work fine for you as well?

**Comment by micahshute** [comment]
Looks good to me! If I run into any issues locally, I'll let you know @maxwellbenton
